STMFixedAssetsWebsite/Controllers/WFD01020Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using th.co.toyota.stm.fas.BusinessObject;
using th.co.toyota.stm.fas.BusinessObject.Common;
using th.co.toyota.stm.fas.Models.Common;
using th.co.toyota.stm.fas.Models.SFAS.WFD01020;


namespace th.co.toyota.stm.fas.Controllers
{
    public class WFD01020Controller : BaseController
    {
        private WFD01020BO bo;

        protected WFD01020BO BO
        {
            get
            {
                if (bo == null) bo = new WFD01020BO();
                return bo;
            }
        }
       
        /*
        public ActionResult Index()
        {
            ViewBag.EMP_CODE = GlobalUser.UserSc2.TFASTEmployeeNo;
            return View();
        }
        */
        public ActionResult Index (string CATEGORY, string SUB_CATEGORY, string MODE)
        {
            if (!base.CheckResignUser())
            {
                return RedirectToAction("ErrorPage", "Errors", new { MessageCode = "MFAS1910AERR" });

            }

            ViewBag.EMP_CODE = GlobalUser.UserSc2.TFASTEmployeeNo;
            ViewBag.CATEGORY = CATEGORY;
            ViewBag.SUB_CATEGORY = SUB_CATEGORY;
            ViewBag.MODE = MODE;


   
            if (UserPrincipleBO.IsAccessButton("WFD01020Edit", GlobalUser.UserSc2.Acl))
            {
                ViewBag.IsEnableButtonWFD01020Edit = "Y";
            }
            else
            {
                ViewBag.IsEnableButtonWFD01020Edit = "N";
            }
      
            return View();
        }      

        public ActionResult ManageSystem(string CATEGORY, string SUB_CATEGORY, string CODE)
        {
            ViewBag.EMP_CODE = GlobalUser.UserSc2.TFASTEmployeeNo;
            ViewBag.CATEGORY = CATEGORY;
            ViewBag.SUB_CATEGORY = SUB_CATEGORY;
            ViewBag.CODE = CODE;
            ViewBag.MODE = (string.IsNullOrWhiteSpace(CODE)? "ADD": "UPDATE");

            return View();
        }

        [HttpPost]
        public JsonResult LoadCategorySys()
        {
            var result = new WFD01020BO().GetCategory();
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult LoadSubCategorySys(string data)
        {
            var result = new WFD01020BO().GetSubCategory(data);
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult SearchSystemMaster(WFD01020DataModel con, PaginationModel page)
        {
            return SearchJson(new WFD01020BO().SearchSystemMaster(con, page));
        }

        [HttpPost]
        public JsonResult GetSystemMaster(WFD01020DataModel data)
        {
            return BaseJson(new WFD01020BO().GetSystemMaster(data));                    
        }

        [HttpPost]
        public JsonResult InsertSystemMaster(WFD01020DataModel data)
        {
            return BaseJson(BO.InsertSystemMaster(data));
        }

        [HttpPost]
        public JsonResult UpdateSystemMaster(WFD01020DataModel data)
        {
            return BaseJson(BO.UpdateSystemMaster(data));
        }

        [HttpPost]
        public JsonResult ValidateSystemMaster(WFD01020DataModel data)
        {
            return BaseJson(new WFD01020BO().ValidateSystemMaster(data));
        }
    }
}

STMFixedAssetsWebsite/Views/WFD01020/Index.cshtml
@{
    ViewBag.ScreenTitle = "System Master";
}

<style>
    .notextindent > th {
        text-indent: 0px;
    }
    table.dataTable thead > tr > th {
        padding-left:15px;
        padding-right:15px;
        text-align:center;
    }
    p {
        margin:0px;
    }
    .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
        padding:7px 10px 7px 4px;    
    }
    .table-responsive {
        min-height: 0.01%;
        overflow-x:hidden;
    }

    .table-responsive > div:first-child > div:nth-child(2){
        overflow-x:auto;
        margin-right: 0px;
    }

    .table-responsive > div:first-child{
        margin-right: 0px;
    }
</style>

<form class="form-horizontal" id="form">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Search Condition</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body" style="display: block;">
            <div class="col-sm-12">
                <div class="box-default">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="cbbCategory" class="col-sm-1 text-right control-label">Category</label>
                                <div class="col-sm-3">
                                    <select id="cbbCategory" class="form-control select2 requied">
                                        <option>&nbsp;</option>
                                    </select>
                                </div>
                                <label for="cbbSubCategory" class="col-sm-2 text-right control-label">Sub-Category</label>
                                <div class="col-sm-3">
                                    <select id="cbbSubCategory" class="form-control select2 requied">
                                        <option>&nbsp;</option>
                                    </select>
                                </div>
                                <div class="col-sm-3" style="text-align:right">
                                    @Html.Button("WFD01020Search", "Search", new { @class = "btn btn-primary", type = "button" }, TagHelper.BUTTON_TYPES.SEARCH)
                                    @Html.Button("WFD01020Clear", "Clear", new { @class = "btn btn-warning", type = "button" }, TagHelper.BUTTON_TYPES.CLEAR)
                                </div>
                            </div>
                            @*<div class="form-group">
                                        <div class="form-inline from-in text-right">
                                            @*<button class="btn btn-primary" id="WFD01020Search" type="button"><i class="fa fa-search"></i>@TagHelper.BUTTON_TYPES.SEARCH</button>
                                                <button class="btn btn-warning" id="WFD01020Clear" type="button"><i class="fa fa-refresh"></i>@TagHelper.BUTTON_TYPES.CLEAR</button>

                                        </div>
                                </div>*@
                        </div>
                    </div>
                </div>
            </div> <!-- End row condition panel -->
        </div>
    </div>
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">
                Search Result
            </h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body" style="display: block;">
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="form-inline from-in text-right">
                        @*<button class="btn btn-info" id="WFD01020Add" type="button"><i class="fa fa-plus"></i>@TagHelper.BUTTON_TYPES.ADD</button>*@

                        @Html.Button("WFD01020Add", "Add", new { @class = "btn btn-info", type = "button" }, TagHelper.BUTTON_TYPES.ADD)
                    </div>
                </div>
                <div class="form-group" id="SearchResult">
                    <div class="table-responsive">
                        <table id="tableSystemMaster" class="table table-bordered table-striped table-hover table-th-center" style="border-radius:3px;font-size:12px;">
                            <thead class="bg-gray">
                                <tr class="notextindent">
                                    <th style="width:90px">Category</th>
                                    <th style="width:100px">Sub-Category</th>
                                    <th style="width:100px">Code</th>
                                    <th style="width:250px">Value</th>
                                    <th style="width:30px">Active</th>
                                    <th style="width:150px">Remark</th>
                                    <th style="width:30px">Edit</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section scripts {
    <script>
        var URL_CONST = {
            Mode: 'SEARCH',
            InitURL: '@Url.Action("", "WFD01020")',
            CategoryURL: '@Url.Action("LoadCategorySys", "WFD01020")',
            SubCategoryURL: '@Url.Action("LoadSubCategorySys", "WFD01020")',
            SearchURL: '@Url.Action("SearchSystemMaster", "WFD01020")',
            ManageSystem: '@Url.Action("ManageSystem", "WFD01020")',
            ValidateSysURL: '@Url.Action("ValidateSystemMaster", "WFD01020")',
            EmployeeCode: '@ViewBag.EMP_CODE',
            EditText: '@TagHelper.BUTTON_TYPES.EDIT',
            Category: '@ViewBag.CATEGORY',
            SubCategory: '@ViewBag.SUB_CATEGORY',
            Mode: '@ViewBag.MODE',
        }
        var WFD01020_Param =
            {
                IsEnableButtonWFD01020Edit: '@ViewBag.IsEnableButtonWFD01020Edit'
            }

    </script>
    <script type="text/javascript" src="~/JS/WFD01020.js"></script>
}

STMFixedAssetsWebsite/Views/WFD01020/ManageSystem.cshtml
@{
    ViewBag.Title = "System Master";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.ScreenTitle = "System Master";
}

<form class="form-horizontal" id="form">
    <div class="box">
        <div class="box-body" style="display: block;">
            <div class="row" id="Condition" style="margin-top: 20px;">
                <div class="col-md-12">               
                    
                    <div class="form-group">
                        <label for="cbbTypeOfReport" class="col-sm-2 text-right">Category</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" id="txtCategory" 
                                   name="txtCategory" readonly />
                        </div>
                        <label for="cbbCategory" class="col-sm-2 text-right">Sub-Category</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" id="txtSubCategory"
                                   name="txtSubCategory" readonly />
                        </div>                       
                    </div>
                  
                    <div class="form-group">
                        <label for="txtCode" class="col-sm-2 text-right">Code</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control require" id="txtCode"
                                   name="txtCode" />
                        </div>                       
                    </div>

                    <div class="form-group">
                        <label for="txtValue" class="col-sm-2 text-right">Value</label>
                        <div class="col-sm-8">                       
                            <textarea  rows="6"  class="form-control require" id="txtValue"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="txtRemark" class="col-sm-2 text-right">Remarks</label>
                        <div class="col-sm-8">                          
                            <textarea rows="6"  class="form-control" id="txtRemark"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="txtRemark" class="col-sm-2 text-right">Active</label>
                        <div class="col-sm-3">
                         <input type="checkbox" id="chkActive"/>
                        </div>
                    </div>

                    <div class="form-group">                       
                        <div class="button-box navbar-right">                          
                            @*<button class="btn btn-success" id="WFD01020Save" type="button"><i class="fa fa-save"></i>@TagHelper.BUTTON_TYPES.SAVE</button>
                            <button class="btn btn-warning" id="WFD01020Cancel" type="button"><i class="fa fa-close"></i>@TagHelper.BUTTON_TYPES.CANCEL</button>*@   
                            @Html.Button("WFD01020Save", "Save", new { @class = "btn btn-success" }, TagHelper.BUTTON_TYPES.SAVE)
                            @Html.Button("WFD01020Cancel", "Cancel", new { @class = "btn btn-warning" }, TagHelper.BUTTON_TYPES.CANCEL)
                              
                                 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-footer-->
    </div>
</form>



@section scripts {
    <script>
        var URL_CONST = {
            Mode: 'ITEM',
            Category: '@ViewBag.CATEGORY',
            SubCategory: '@ViewBag.SUB_CATEGORY',
            Code: '@ViewBag.CODE',
            EmployeeCode: '@ViewBag.EMP_CODE',
            State: '@ViewBag.MODE',
            InitURL: '@Url.Action("", "WFD01020")',
            GetSystemMasterURL: '@Url.Action("GetSystemMaster", "WFD01020")',
            InsertSystemMasterURL: '@Url.Action("InsertSystemMaster", "WFD01020")',
            UpdateSystemMasterURL: '@Url.Action("UpdateSystemMaster", "WFD01020")'
        }

    </script>
    <script type="text/javascript" src="~/JS/WFD01020.js"></script>
}

       