STMFixedAssetsWebsite/Controllers/WFD02410Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using th.co.toyota.stm.fas.BusinessObject;
using th.co.toyota.stm.fas.Models.WFD02410;
using th.co.toyota.stm.fas.Models.Common;
using th.co.toyota.stm.fas.Models;
using th.co.toyota.stm.fas.Models.COMSCC;

namespace th.co.toyota.stm.fas.Controllers
{
    public class WFD02410Controller : BaseController
    {
        // GET: WFD02410
        public ActionResult Index(WFD0BaseRequestDocModel data)
        {
            //Initial
            data.USER_BY = GlobalUser.UserSc2.TFASTEmployeeNo;
            this.BusinessLogic.init(data);

            //Check Is require TMC
            ViewBag.MSTD0059AERR = this.BusinessLogic.GetSystemMessage(Constants.MESSAGE.MSTD0059AERR, null).VALUE;
            return PartialView();
        }

        private WFD02410BO bo;
        protected WFD02410BO BusinessLogic
        {
            get
            {
                if (bo == null) bo = new WFD02410BO();
                return bo;
            }
        }
        [HttpPost]
        public JsonResult SearchCostCenter(COMSCCDefaultScreenModel con, PaginationModel page)
        {
            var _result = this.BusinessLogic.SearchCostCenter(con, page);
            return SearchJson(_result, page);
            
        }

        [HttpPost]
        public JsonResult GetNewAssetOwner(WFD02410HeaderModel con)
        {
            var _rs = this.BusinessLogic.GetNewAssetOwnerTransfer(con);
            return BaseJson(_rs);            
        }
        [HttpPost]
        public JsonResult WFD02410_IsMassPermission(WFD0BaseRequestDocModel con)
        {
            // CheckMassPermission
            return BaseJson((new WFD02510BO()).CheckMassPermission(con));
        }
        [HttpPost]
        public JsonResult GetAssetList(WFD0BaseRequestDocModel con, PaginationModel page)
        {
            var _result = this.BusinessLogic.GetAssetList(con, page);
            return SearchJson(_result, page);
        }

        [HttpPost]
        public JsonResult AddAsset(List<WFD0BaseRequestDetailModel> data)
        {
            var _rs = this.BusinessLogic.InsertAsset(data);
            return BaseJson(_rs);
        }


        [HttpPost]
        public JsonResult ClearAssetsList(WFD0BaseRequestDocModel data)
        {
            var _rs = this.BusinessLogic.ClearAssetList(data);
            return BaseJson(_rs);
        }

        [HttpPost]
        public JsonResult DeleteAsset(WFD0BaseRequestDetailModel data)
        {
            var _rs = this.BusinessLogic.DeleteAsset(data);
            return BaseJson(_rs);
        }

        // Operation when user click button on request master screen
        // 1270.js call request.JS -> collect data -> this function and return data to main screen
        [HttpPost]
        public JsonResult Prepare(WFD0BaseRequestDocModel data)
        {
            var _rs = this.BusinessLogic.PrepareCostCenterToGenerateFlow(data);
            return BaseJson(_rs);
        }

        [HttpPost]
        public JsonResult UpdateAssetList(WFD02410HeaderModel _data)
        {
            var _rs = this.BusinessLogic.UpdateAssetList(_data, GlobalUser.UserSc2.TFASTEmployeeNo);
            return BaseJson(_rs);
        }

        [HttpPost] //data in dropdown transfer reason 
        public JsonResult GetTransferReason(WFD02410Model data)
        {
            var d = this.BusinessLogic.GetTransferReason(data);
            return BaseJson(d);
        }
        [HttpPost] //data in dropdown Location
        public JsonResult GetDropdownLocation(WFD02410Model data)
        {
            var d = this.BusinessLogic.GetDropdownLocation(data);
            return BaseJson(d);
        }
        [HttpPost] //data in dropdown WBSCosProject CostCenter
        public JsonResult GetDropdownWBSCosProject(WFD02410Model data)
        {
            var d = this.BusinessLogic.GetDropdownWBSCosProject(data);
            return BaseJson(d);
        }
        [HttpPost] //data in dropdown ToEmployee
        public JsonResult GetDropdownToEmployee(WFD02410NewAssetOwnerModel data)
        {
            var d = this.BusinessLogic.GetDropdownToEmployee(data);
            return BaseJson(d);
        }

        [HttpPost] 
        public JsonResult Resend(Models.WFD01270.WFD01170MainModel header, WFD02410HeaderModel data)
        {
            var d = this.BusinessLogic.Resend(header, data, GlobalUser.UserSc2.TFASTEmployeeNo);
            return BaseJson(d);
        }


    }
}

STMFixedAssetsWebsite/Views/WFD02410/CostCenterPopup.cshtml
@{
    ViewBag.Title = "CostCenterPopup";
}
<style>
    /*table.dataTable thead > tr > th {
        padding-right: 20px;
        padding-left: 20px;
    }

    .input-group-addon {
        border-left-width: 0px;
    }

    .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
        padding: 8px 5px;
    }*/

    .cursorPointer {
        cursor: pointer;
    }

    #CostSearchResultTable-item-per-page {
        min-width:50px;
    }
</style>
<div class="modal fade" id="divSearchCostCenter" tabindex="99" role="dialog">
    <div class="modal-dialog" style="width:1000px; margin-top:20px;">
        <div class="modal-content Radius12">
            <div class="modal-header">
                <button id="comCC2410CloseModal" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="lblCostCenterTitle">Search Cost Center Dialog</h4>
            </div>
            <div class="modal-body">
                <div id="AlertMessagecomCC2410" class="message-area">
                </div>
                <div class="form-horizontal">
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">
                                Search Condition
                            </h3>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="FIND" class="col-sm-1 control-label">Find :</label>
                                    <div class="col-sm-8">
                                        @Html.CommonTextBox("FIND", null, new { @class = "form-control", style = "width: 100%;" })
                                    </div>
                                    <div class="col-sm-3 text-right">
                                        <button id="btnCC2410Search" class="btn btn-primary"><i class="fa fa-search"></i>  Search </button>
                                        <button id="btnCC2410Close" class="btn btn-warning"><i class="fa fa-power-off"></i>  Close </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box box-success" id="CostSearchDataRow">
                    <div class="box-header with-border">
                        <h3 class="box-title">
                            Search Result
                        </h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div id="CostSearchResult" class="col-lg-12">
                            <table id="CostSearchResultTable" class="table table-bordered table-striped table-hover table-th-center" style="margin-top: 10px; font-size:12px; border-radius: 3px;">
                                <thead style="height:40px;">
                                    <tr>
                                        <th style="width:100px;">Cost Code</th>
                                        <th style="min-width: 150px; text-align:center;">Cost Name</th>
                                        <th style="width:150px;" id="lblHeader">FA Window Name</th>
                                        <th style="width:100px;">Status</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

STMFixedAssetsWebsite/Views/WFD02410/DetailTransDialog.cshtml
<div class="modal fade" id="divDetailTransDialog" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header HeaderModel">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="lblAssetNoOnDetailTransDialog"></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label for="WFD02410ComBoLocation" class="col-sm-4 control-label">Location :</label>
                        <div class="col-sm-8">
                            <select id="WFD02410ComBoLocation" class="form-control select2" style="width:100%"></select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label for="WFD02410FutureUse" class="col-sm-4 control-label">Future Use :</label>
                        <div class="col-sm-8">
                            <input id="WFD02410FutureUse" disabled="disabled" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label for="WFD02410ComBoWBSCosProject" class="col-sm-4 control-label">WBS Cost (Project) :</label>
                        <div class="col-md-8">
                            <select id="WFD02410ComBoWBSCosProject" class="form-control select2" style="width:100%"></select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label for="WFD02410ComBoToEmployee" class="col-sm-4 control-label">Assign Employee :</label>
                        <div class="col-md-8">
                            <select id="WFD02410ComBoToEmployee" class="form-control select2" style="width:100%"></select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label for="WFD02410LocationDetail" class="col-sm-4 control-label">Location Detail :</label>
                        <div class="col-sm-8">
                            <input id="WFD02410LocationDetail" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="RadiusBottom12" style="text-align:right;">
                    <div class="form-inline form-in" style="margin: 10px 46px;">
                        <div class="navbar-right">
                            <button class="btn btn-sm btn-info" style="width: 80px;" id="btnDetailTransDialogOK" type="button"><i class="fa fa-save"></i> OK </button>
                            <button class="btn btn-sm btn-warning" data-dismiss="modal" id="btnCancelDialog" type="button"><i class="fa fa-ban"></i> Cancel </button>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

</div>

STMFixedAssetsWebsite/Views/WFD02410/Index.cshtml
<script>
    var UrlWFD02410 = {
        //WFD02410
        GetTransferReason: '@Url.Action("GetTransferReason", "WFD02410")',
        GetDropdownWBSCosProject: '@Url.Action("GetDropdownWBSCosProject", "WFD02410")',
        GetDropdownToEmployee: '@Url.Action("GetDropdownToEmployee", "WFD02410")',
        GetDropdownLocation: '@Url.Action("GetDropdownLocation", "WFD02410")',
        GetNewAssetOwner: '@Url.Action("GetNewAssetOwner", "WFD02410")',

        SearchCostCenter: '@Url.Action("SearchCostCenter", "WFD02410")',
    }
    var URL_COMSCC = {
        ITEM_PER_PAGE : 10
    }
    
    var Message = {
        MSTD0059AERR : '@ViewBag.MSTD0059AERR'
    }
</script>
<style>
    p {
        margin: 0 0 0px !important;
    }
</style>
<div class="box box-primary" id="WFD02410_NewAssetOwner">
    <div class="box-header with-    ">
        <h3 class="box-title">New Asset Owner</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-sm-12">
            <div class="form-group">
                <label for="WFD02410_NEW_OWNER_EMP_CODE" class="col-sm-2 control-label padding-label">Employee Code</label>
                <div class="col-sm-2 padding-group-textbox">
                    @Html.CommonTextBox("WFD02410_NEW_OWNER_EMP_CODE", null, new { @class = "form-control", style = "width: 100%;", disabled = "disabled", maxlength = "11" })
                </div>
                <label for="WFD02410_NEW_OWNER_EMP_NAME" class="col-sm-1 control-label padding-label">Name</label>
                <div class="col-sm-3 padding-group-textbox">
                    @Html.CommonTextBox("WFD02410_NEW_OWNER_EMP_NAME", null, new { @class = "form-control", style = "width: 100%;", disabled = "disabled", maxlength = "8" })
                </div>
                <label for="WFD02410_NEW_OWNER_COST_NAME" class="col-sm-1 control-label  padding-label">Cost Center</label>
                <div class="col-sm-3 padding-group-textbox">
                    <div class="input-group">
                        <input type="text" class="form-control" id="WFD02410_CHECK_DIALOG_COST_CODE" name="CHECK_DIALOG_COST_CODE" style="display:none;" maxlength="50" pattern="^[A-Za-z0-9\-]{0,15}$">
                        <input type="text" class="form-control" id="WFD02410_NEW_OWNER_COST_CODE" name="COST_CODE" style="display:none;" maxlength="50" pattern="^[A-Za-z0-9\-]{0,15}$">
                        <input type="text" class="form-control" id="WFD02410_NEW_OWNER_COST_NAME" name="COST_NAME" maxlength="70" pattern="^[A-Za-z0-9\-]{0,15}$" tabindex="2" readonly="readonly">
                        <span class="input-group-btn" style="cursor:pointer;"><button id="WFD02410BtnNEW_OWNER_COST_NAME" class="btn btn-flat" type="button" style="background-color:white; padding-left:8px; padding-right:8px;">...</button></span>
                    </div>
                </div>                
            </div>
            <div class="form-group">
                <label for="WFD02410_NEW_OWNER_RESP_COST_NAME" class="col-sm-2 control-label padding-label">Responsible Cost Center</label>
                <div class="col-sm-2 padding-group-textbox">
                    <div class="input-group">
                        <input type="text" class="form-control" id="WFD02410_CHECK_DIALOG_RESP_COST_CODE" name="CHECK_DIALOG_RESP_COST_CODE" style="display:none;" maxlength="50" pattern="^[A-Za-z0-9\-]{0,15}$">
                        <input type="text" class="form-control" id="WFD02410_NEW_OWNER_RESP_COST_CODE" name="COST_CODE" style="display:none;" maxlength="50" pattern="^[A-Za-z0-9\-]{0,15}$">
                        <input type="text" class="form-control" id="WFD02410_NEW_OWNER_RESP_COST_NAME" name="COST_NAME" maxlength="70" pattern="^[A-Za-z0-9\-]{0,15}$" tabindex="2" readonly="readonly">
                        <span class="input-group-btn" style="cursor:pointer;"><button id="WFD02410BtnNEW_OWNER_RESP_COST_NAME" class="btn btn-flat" type="button" style="background-color:white; padding-left:8px; padding-right:8px;">...</button></span>
                    </div>
                </div>
                <label for="WFD02410_NEW_OWNER_POS_NAME" class="col-sm-1 control-label  padding-label">Position</label>
                <div class="col-sm-3 padding-group-textbox">
                    @Html.CommonTextBox("WFD02410_NEW_OWNER_POS_NAME", null, new { @class = "form-control", style = "width: 100%;", disabled = "disabled", maxlength = "70" })
                </div>                
                <label for="DEPT_NAME" class="col-sm-1 control-label  padding-label">Department</label>
                <div class="col-sm-3 padding-group-textbox">
                    @Html.CommonTextBox("WFD02410_NEW_OWNER_DEPT_NAME", null, new { @class = "form-control", style = "width: 100%;", disabled = "disabled", maxlength = "45" })
                </div>                                  
            </div>
            <div class="form-group">
                <label for="PHONE_NO" class="col-sm-2 control-label  padding-label">Tel No.</label>
                <div class="col-sm-2 padding-group-textbox">
                    @Html.CommonTextBox("WFD02410_NEW_OWNER_PHONE_NO", null, new { @class = "form-control", style = "width: 100%;", disabled = "disabled", maxlength = "20" })
                </div>
                <label for="SECT_NAME" class="col-sm-1 control-label  padding-label">Section</label>
                <div class="col-sm-3 padding-group-textbox">
                    @Html.CommonTextBox("WFD02410_NEW_OWNER_SECT_NAME", null, new { @class = "form-control", style = "width: 100%;", disabled = "disabled", maxlength = "45" })
                </div>               
            </div>  
        </div>
    </div>
</div>
<div class="box box-primary" id="WFD02410_ApproveRouteType">
    <div class="box-header with-border">
        <div class="row">
            <div class="col-md-4"><h3 class="box-title">Approve Route Type</h3></div>
            <div class="col-md-2" custom-control custom-checkbox">
                <input id="chkNormal" type="checkbox" class="custom-control-input" tabindex="3" style="width:24px;height:24px;" />
                <label class="custom-control-label" for="chkNormal">Normal</label>
            </div>
            <div class="col-md-4" custom-control custom-checkbox">
                <input id="chkMass" type="checkbox" class="custom-control-input" tabindex="3" style="width:24px;height:24px;" />
                <label class="custom-control-label" for="chkMass">Mass</label>
            </div>
        </div>
    </div>
</div>
<div class="box box-primary" id="WFD02410_SearchDataRow">
    <div class="box-header with-border">
        <h3 class="box-title">Assets List</h3>
        <div class="form-group">
            <div class="col-sm-6">
                @Html.WFD01170Button("btnRequestDownload", "Download Template ", new { @class = "btn btn-info", tabindex = "2" }, TagHelper.BUTTON_TYPES.DOWNLOAD)
                @Html.WFD01170Button("btnRequestUpload", "Upload Excel ", new { @class = "btn btn-warning", tabindex = "2" }, TagHelper.BUTTON_TYPES.UPLOAD)
            </div>
            <div class="col-sm-6 text-right">
                @Html.WFD01170Button("btnRequestAdd", "Add ", new { @class = "btn btn-info", tabindex = "2" }, TagHelper.BUTTON_TYPES.ADD)
                @Html.WFD01170Button("btnRequestClear", "Clear ", new { @class = "btn btn-warning", tabindex = "2" }, TagHelper.BUTTON_TYPES.CLEAR)
                @Html.WFD01170Button("btnRequestExport", "Export to Excel ", new { @class = "btn btn-info", tabindex = "2" }, TagHelper.BUTTON_TYPES.EXPORT)
            </div>
        </div>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>

    </div>
    <div class="box-body">
        <div class="row">
            
            <div id="divSearchRequestResult" class="col-lg-12">
                <table id="tbSearchResult" class="table table-bordered table-striped table-hover table-thead-center"
                       style="font-size:12px; border-radius: 3px;">
                    <thead style="height:40px; background-color:rgba(236, 240, 245, 1);">
                        <tr>
                            <th style="width: 25px; text-align: center;"><input id="WFD02410_SelectAll" type="checkbox" style="margin-top: 3px; height:20px; width:20px;" /></th>
                            <th style="width: 20px; text-align: center;">No.</th>
                            <th style="width: 80px; text-align: center;">Asset No.</th>
                            <th style="width: 40px; text-align: center;">Asset Sub</th>
                            <th style="width: 120px; text-align: center;">Asset Name</th>
                            <th style="width: 40px; text-align: center;">Date In Service</th>
                            <th style="width: 80px; text-align: center;">Cost</th>
                            <th style="width: 80px; text-align: center;">Book Value</th>
                            <th style="width: 80px; text-align: center;">Transfer Reason</th>
                            <th style="width: 110px; text-align: center;">Effective Date</th>
                            <th style="width: 25px; text-align: center;">BOI</th>
                            <th style="width: 35px; text-align: center;">Tax<br />Priviledge</th>
                            <th style="width: 25px; text-align: center;">BOI<br />Doc</th>
                            <th style="width: 40px; text-align: center;">Status</th>
                            <th style="width: 25px; text-align: center;"></th>
                            <th style="width: 25px; text-align: center;">Del</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div class="row">
            <div id="WFD02210RemarkGenerate" class="col-lg-12" style="display:none;">
                <div class="form-group" style="padding-right:16px; color:#e08e0b; text-align:right">
                    <p>Remark: If you want to edit data in asset list, please click Reset Approver List.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="box box-primary" id="DivTMCDocument">
    <div class="box-header with-border">
        <div class="row">
            <div class="col-sm-10" style="text-align:left;">
                <h3 class="box-title">TMC Document</h3>
            </div>

            <div class="col-sm-2" style="text-align:right;">
                <button id="WFD02410btnUploadTMCDocument" type="button" class="btn btn-info" tabindex="21"><i class="fa fa-upload"></i> Upload </button>
            </div>

        </div>
    </div>
  
</div>

@Html.Partial("CostCenterPopup")
@Html.Partial("DetailTransDialog")

<div class="modal fade" id="WFD02410_SetOtherReason" tabindex="1" role="dialog">
    <div class="modal-dialog" style="width:520px; margin: 80px auto;">
        <div class="modal-content Radius12" style="width:700px;">
            <div class="modal-header HeaderModel">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="btnWFD02410_SetOtherReasonCloseModal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Transfer Reason (Other)</h4>
            </div>
            <div class="fasdangerPopup alert alert-dismissible" id="WFD02410MessageAlertReasonOther" style="display:none">
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input id="WFD02410_TRNF_REASON_OTHER" class="form-control require" style="width:100%" maxlength="200" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <button id="WFD02410_TRNF_REASON_OTHER_SAVE" class="btn btn-success"><i class="fa fa-save"></i>  Save </button>
                    <button id="WFD02410_TRNF_REASON_OTHER_CANCEL" class="btn btn-warning"><i class="fa fa-close"></i>  Cancel </button>
                </div>
            </div>
        </div>
    </div>
</div>

STMFixedAssetsWebsite/Views/WFD02410/TransferRequest.cshtml
<style>
    .RetiredRead {
        background-color: rgba(221, 75, 57, 0.8);
        color:#333;
    }
    p {
        margin:0px;
    }
    .btn > i {
     margin-right: 0px;
}
    .table-thead-center th {
    text-align:center;
    }
    .btn-del-file {
        display:inline-block;
        margin-left:5px;
    }
    .btn-white {
        background-color:white;
        color:black;
    }
    .btn-view-file {
        background-color:white;
        color:black;
        padding-right:5px;
        display:inline-block;
        border-color:black;
    }
    .inlineBlock {
        display:inline-block;       
    }
     .RetiredRead a {
    /*color:#333;*/
    }
</style>
<div class="box box-primary" id="WFD02410_SearchDataRow">
    <div class="box-header with-border">
        <h3 class="box-title">Assets List</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="col-sm-4">
                    </div>
                    <div class="col-sm-8 text-right">
                        <button id="WFD02410PrintAddAssets" class="btn btn-info" tabindex="4"><i class="fa fa-print"></i> Print</button>
                        @Html.Button("WFD02410AddAssets", "Add ", new { @class = "btn btn-info", tabindex = "4" }, TagHelper.BUTTON_TYPES.ADD)
                        @Html.Button("WFD02410Clear", "Clear ", new { @class = "btn btn-warning", tabindex = "4" }, TagHelper.BUTTON_TYPES.CLEAR)
                        @Html.Button("WFD02410ExportToExcel", "Export to Excel ", new { @class = "btn btn-info", tabindex = "4" }, TagHelper.BUTTON_TYPES.EXPORT)
                    
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div id="WFD02410_SearchResult" class="col-lg-12">
                <table id="WFD02410_SearchResultTable" class="table table-bordered table-striped table-hover table-thead-center"
                       style="margin-top: 10px; font-size:12px; border-radius: 3px;">
                    <thead style="height:40px; background-color:rgba(236, 240, 245, 1);">
                        <tr>
                            <th style="width: 110px;">Asset No</th>
                            <th style="min-width: 150px;">Asset Name</th>
                            <th style="width: 75px;">Date In Service</th>
                            <th style="width: 90px;">Cost</th>
                            <th style="width: 90px;">Book Value</th>
                            <th style="min-width: 100px;">Transfer Reason</th>
                            <th style="min-width: 70px;">BOI No</th>
                            <th style="width: 60px;">BOI</th>
                            <th style="width: 70px;">BOI Doc</th>
                            <th style="min-width: 25px;"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div class="row">
            <input id="WFD02410FileUploadFile" type="file" class="form-control" style="display:none" />
        </div>
        <div class="row">
            <div id="WFD02410RemarkGenerate" class="col-lg-12" style="display:none;">
                <div class="form-group" style="padding-right:16px; color:#e08e0b; text-align:right">
                    <p>Remark: If you want to edit data in asset list, please click Reset Approver List.</p>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("../WFD02190/Index")