STMFixedAssetsWebsite/Controllers/COMSCCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using th.co.toyota.stm.fas.BusinessObject;
using th.co.toyota.stm.fas.Models.COMSCC;
using th.co.toyota.stm.fas.Models.Common;

namespace th.co.toyota.stm.fas.Controllers
{
    public class COMSCCController : BaseController
    {
        // GET: COMSCC
        private COMSCCBO bo;
        protected COMSCCBO BO
        {
            get
            {
                if (bo == null) bo = new COMSCCBO();
                return bo;
            }
        }

        [HttpPost]
        public JsonResult Index(string EmpCode,string CostCode,string AllCostCode, string AssetOwnerFlag,string PageRequest)
        {
            COMSCCDefaultScreenModel _Para = new COMSCCDefaultScreenModel();
            _Para.ALL_COST_CENTER = AllCostCode;
            _Para.EMP_CODE = EmpCode;
            _Para.COST_CODE = CostCode;
            _Para.AssetOwnerFlag = AssetOwnerFlag;
            _Para.PAGE_REQUEST = PageRequest;
            return BaseJson(_Para);
        }

        public ActionResult Index()
        {            
            return View();
        }

        [HttpPost]
        public JsonResult COMSCC_Search(COMSCCDefaultScreenModel con, PaginationModel page)
        {
            if (con.EMP_CODE == null || con.EMP_CODE == "")
            {
                con.EMP_CODE = GlobalUser.UserSc2.TFASTEmployeeNo;
            }
            return SearchJson(BO.Search(con, page));
        }
    }
}

STMFixedAssetsWebsite/Views/COMSCC/Index.cshtml
<style>
    /*table.dataTable thead > tr > th {
        padding-right: 20px;
        padding-left: 20px;
    }*/

    .input-group-addon {
        border-left-width: 0px;
    }

    /*.table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
        padding: 8px 5px;
    }*/
    .cursorPointer {
        cursor:pointer;
    }
    /*table.table-bordered, table.table-bordered {
        border-color: rgba(238, 238, 238, 1) !important;
    }

        table.table-bordered, table.table-bordered > thead > tr > th {
            border-color: rgba(238, 238, 238, 1) !important;
        }

            table.table-bordered, table.table-bordered > tbody > tr > td {
                border-color: rgba(238, 238, 238, 1) !important;
            }*/
</style>
<div class="modal fade" id="SearchCostCenter" tabindex="99" role="dialog">
    <div class="modal-dialog" style="width:1000px; margin-top:20px;">
        <div class="modal-content Radius12">
            <div class="modal-header">
                <button id="COMSCCCloseModal" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="lblCostCenterTitle">Search Cost Center Dialog</h4>
            </div>
            <div class="modal-body">
                <div id="AlertMessageCOMSCC" class="message-area">
                </div>
                <div class="form-horizontal">
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">
                                Search condition
                            </h3>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="FIND" class="col-sm-1 control-label">Find :</label>
                                    <div class="col-sm-8">
                                        @Html.CommonTextBox("FIND", null, new { @class = "form-control", style = "width: 100%;" })
                                        <input id="COMSCC_EMP_CODE" type="text" class="form-control" style="display:none" />
                                        <input id="COMSCC_COST_CODE" type="text" class="form-control" style="display:none" />
                                        <input id="COMPANY_" type="text" class="form-control" style="display:none"/>
                                        <input id="COMSCC_ALL_COST_CENTER" type="text" class="form-control" style="display:none" />
                                        <input id="AssetOwnerFlag" type="text" class="form-control" style="display:none" />
                                        <input id="COMSCCPageRequest" type="text" class="form-control" style="display:none" />@*2017-06-09 Suphachai L. Support case BOI User*@
                                    </div>
                                    <div class="col-sm-3 text-right">
                                        <button id="COMSCCSearch" class="btn btn-primary"><i class="fa fa-search"></i>  Search </button>
                                        <button id="COMSCCClose" class="btn btn-warning"><i class="fa fa-power-off"></i>  Close </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box box-success" id="CostSearchDataRow">
                    <div class="box-header with-border">
                        <h3 class="box-title">
                            Search Result
                        </h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div id="CostSearchResult" class="col-lg-12">
                            <table id="CostSearchResultTable" class="table table-bordered table-striped table-hover table-th-center" style="margin-top: 10px; font-size:12px; border-radius: 3px;">
                                <thead style="height:40px;">
                                    <tr>
                                        <th style="width:100px;">Cost Code</th>
                                        <th style="min-width: 150px; text-align:center;">Cost Name</th>
                                        <th style="width:150px;" id="lblHeader">PIC Name</th><!--confirm by Sukanya-->
                                        <th style="width:100px;">Status</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


@section scripts {

    <script type="text/javascript">

        var UserId = '@GlobalUser.UserSc2.TFASTEmployeeNo';
        var URL_CONST = {
            SEARCH_COST_CODE: '@Url.Action("COMSCC_Search", "COMSCC")'
        }

    </script>
}